/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "secondary": "#0058bd",
              "surface-container-low": "#f5f2ff",
              "tertiary-fixed-dim": "#ffb4a7",
              "on-error-container": "#93000a",
              "secondary-container": "#0270ec",
              "secondary-fixed-dim": "#adc6ff",
              "inverse-surface": "#2f2f3b",
              "on-tertiary-fixed": "#400100",
              "tertiary": "#730400",
              "surface-container-high": "#e9e6f6",
              "surface-bright": "#fcf8ff",
              "on-primary-fixed": "#05006d",
              "outline": "#767589",
              "on-primary": "#ffffff",
              "surface": "#fcf8ff",
              "inverse-primary": "#c0c1ff",
              "outline-variant": "#c6c4db",
              "primary-container": "#1a00ff",
              "on-primary-container": "#b6b8ff",
              "on-background": "#1a1b26",
              "surface-tint": "#3b3bff",
              "on-tertiary-fixed-variant": "#920600",
              "on-primary-fixed-variant": "#1700ec",
              "surface-container-lowest": "#ffffff",
              "primary": "#1000bc",
              "primary-fixed-dim": "#c0c1ff",
              "background": "#fcf8ff",
              "surface-container": "#efecfc",
              "error": "#ba1a1a",
              "tertiary-fixed": "#ffdad4",
              "surface-dim": "#dbd8e8",
              "secondary-fixed": "#d8e2ff",
              "on-surface-variant": "#454558",
              "on-error": "#ffffff",
              "error-container": "#ffdad6",
              "surface-variant": "#e3e1f1",
              "inverse-on-surface": "#f1efff",
              "on-tertiary": "#ffffff",
              "on-secondary-container": "#fefcff",
              "on-tertiary-container": "#ffa899",
              "on-surface": "#1a1b26",
              "tertiary-container": "#9e0700",
              "primary-fixed": "#e1e0ff",
              "on-secondary-fixed-variant": "#004494",
              "on-secondary": "#ffffff",
              "surface-container-highest": "#e3e1f1",
              "on-secondary-fixed": "#001a41"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "margin-desktop": "64px",
              "container-max": "1440px",
              "section-gap": "120px",
              "gutter": "24px",
              "unit": "4px",
              "margin-mobile": "20px"
      },
      "fontFamily": {
              "label-md": ["Inter", "sans-serif"],
              "body-lg": ["Inter", "sans-serif"],
              "display-xl": ["Clash Display", "sans-serif"],
              "display-lg": ["Clash Display", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "headline-lg-mobile": ["Clash Display", "sans-serif"],
              "label-sm": ["Inter", "sans-serif"],
              "headline-lg": ["Clash Display", "sans-serif"],
              "headline-md": ["Clash Display", "sans-serif"]
      },
      "fontSize": {
              "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "500"}],
              "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "-0.01em", "fontWeight": "400"}],
              "display-xl": ["72px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "600"}],
              "display-lg": ["56px", {"lineHeight": "1.1", "letterSpacing": "-0.03em", "fontWeight": "600"}],
              "body-md": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
              "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "500"}],
              "label-sm": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "headline-lg": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "500"}],
              "headline-md": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
